services:
  traefik:
    build: .
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - TRAEFIK_LOG_LEVEL=DEBUG
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s