version: '3.8'
services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=/etc/traefik/dynamic-config.yml"
      - "--providers.file.watch=true"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./dynamic-config.yml:/etc/traefik/dynamic-config.yml:ro
    restart: unless-stopped
