http:
  routers:
    homepage-router:
      rule: "PathPrefix(`/homepage`)"
      service: "homepage-service"
      entryPoints:
        - "web"
  
  services:
    homepage-service:
      loadBalancer:
        servers:
          - url: "http://dyzfbakk.home82201.qhph39ns.34m0njpv.com:3000"
        passHostHeader: false
