# config/homepage.yml
http:
  routers:
    homepage-router:
      entryPoints: [web]
      rule: "PathPrefix(`/`)"
      service: homepage-service
      priority: 1
      middlewares:
        - gzip

  services:
    homepage-service:
      loadBalancer:
        servers:
          - url: "http://dyzfbakk.home.qhph39ns.34m0njpv.com"

  middlewares:
    gzip:
      compress: {}