http:
  routers:
    homepage-router:
      entryPoints: [web]
      rule: "Host(`testtraefik1-170350-7-1365954890.sh.run.tcloudbase.com`) && PathPrefix(`/`)"
      service: homepage-service
      priority: 1
      middlewares:
        - gzip

  services:
    homepage-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://dyzfbakk.home.qhph39ns.34m0njpv.com"

  middlewares:
    gzip:
      compress: {}
