# config/homepage.yml  
http:
  routers:
    homepage-router:
      entryPoints: [web]
      rule: "PathPrefix(`/`)"
      service: homepage-service
      priority: 1
      middlewares:
        - gzip
        
  services:
    homepage-service:
      loadBalancer:
        servers:
          - url: "http://dyzfbakk.home.qhph39ns.34m0njpv.com"
        # 可选：启用健康检查
        # healthCheck:
        #   path: "/"
        #   interval: "30s" 
        #   timeout: "5s"