http:
  routers:
    homepage-router:
      entryPoints: [web]
      rule: PathPrefix(`/`)
      service: homepage-service

  services:
    homepage-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://dyzfbakk.home.qhph39ns.34m0njpv.com"
